name: .idp

channels:
  - anaconda
  - conda-forge

dependencies:
  - ipykernel
  - matplotlib
  - openpyxl
  - pandas
  - pip
  - pytables
  - scikit-learn
  - torchmetrics
  - tqdm
  - pip:
    - torch
